name: Update Github Pages branch

on:
  push:
    tags:
      - v*

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Cache NPM dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      - name: Install Dependencies and generate Hexo Site
        run: cd ./hexo && npm install && npm run build
      - name: Make folder for CV/Resume
        run: mkdir -p ./hexo/public/documents/
      - name: Build LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            cv.tex
          working_directory: ./LaTeX
          post_compile: "cp *.pdf ../hexo/public/documents/"
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./hexo/public
